"""
Analytical computation of Lambda_bar for metallic-mean chains using the
Zachary & Torquato (2009) Bragg-peak summation formula:

    Lambda_bar = (2*rho/pi) * sum_{G > 0} I_G / G^2

This is derived from the exact variance formula (their eq. 15 in d=1):
    sigma^2(R) = (rho/pi) * integral S(k) * (2 sin(kR)/k)^2 dk

For a pure Bragg spectrum S(k) = sum_G I_G * delta(k - G), the running average
    Lambda_bar = lim_{R->inf} (1/R) * integral_0^R sigma^2(R') dR'
gives Lambda_bar = (2*rho/pi) * sum_{G>0} I_G / G^2.

This is equivalent to Zachary & Torquato's theta-series method (their eq. 73):
    B_N = lim_{beta->0+} [phi/(2*beta) - (1/2)*sum_k Z_k*r_k*exp(-beta*r_k^2)]
rescaled as Lambda_bar = 2^d * phi * B_N = 2 * phi * B_N at d=1.

Chains treated:
  - Fibonacci  (golden ratio tau = (1+sqrt(5))/2)
  - Silver     (silver ratio sigma = 1+sqrt(2))
  - Bronze     (bronze ratio beta  = (3+sqrt(13))/2)
  - Copper     (copper ratio kappa = 2+sqrt(5))
  - Nickel     (nickel ratio nu    = (5+sqrt(29))/2)

Cross-check: Fibonacci should reproduce Lambda_bar = 0.20110
             (Zachary & Torquato 2009, Table 1).

The script has three methods:
  Method A: Analytical Bragg peak summation using known structure factor
            formula for metallic-mean chains (cut-and-project / eigenfunction
            approach).  Does not require generating the tiling.
  Method B: Large-N FFT of the generated tiling to extract Bragg peak
            positions and intensities numerically, then sum I_G/G^2.
  Method C: Direct variance Monte Carlo (existing approach for comparison).

References:
  Zachary & Torquato (2009) J. Stat. Mech. P12015
  Oguz et al. (2019) -- eigenvalue formula for alpha
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import sys
import os

# ---------------------------------------------------------------------------
# Import project utilities
# ---------------------------------------------------------------------------
sys.path.insert(0, os.path.dirname(__file__))
from substitution_tilings import (CHAINS, generate_substitution_sequence,
                                  sequence_to_points)
from quasicrystal_variance import (compute_number_variance_1d,
                                   compute_lambda_bar)


# ===========================================================================
# BRAGG PEAK INTENSITIES FOR METALLIC-MEAN CHAINS (Analytical)
# ===========================================================================
#
# For the n-th metallic-mean chain (n=1 Fibonacci, n=2 Silver, ...):
#   Substitution: S -> L,  L -> L^n S
#   Matrix: M = [[0, 1], [1, n]]
#   Largest eigenvalue: lambda1 = (n + sqrt(n^2+4)) / 2   (metallic mean)
#   Second eigenvalue:  lambda2 = (n - sqrt(n^2+4)) / 2   (|lambda2| < 1)
#
# The tile lengths in the self-similar basis are:
#   ell_S = 1,   ell_L = lambda1
# (right eigenvector of M normalised so shortest tile = 1)
#
# The frequencies (relative probabilities) come from the LEFT eigenvector:
#   Left eigenvec of M for lambda1:  (1, lambda1)  (unnormalised)
#   f_S = 1 / (1 + lambda1),   f_L = lambda1 / (1 + lambda1)
#
# Mean spacing:
#   ell_bar = f_S * ell_S + f_L * ell_L = (1 + lambda1^2) / (1 + lambda1)
# which simplifies because lambda1^2 = n*lambda1 + 1 (characteristic equation):
#   ell_bar = (1 + n*lambda1 + 1) / (1 + lambda1) = (2 + n*lambda1)/(1+lambda1)
#
# Density: rho = 1 / ell_bar
#
# STRUCTURE FACTOR / BRAGG PEAKS:
# For a one-dimensional quasiperiodic tiling generated by cut-and-project from
# Z^2 with the cut window defined by the substitution, the Bragg peaks lie at
# wavevectors
#
#   G_{m,n} = 2*pi / ell_bar * (m + n / lambda1)
#
# for (m, n) integers, not both zero.  The intensities are given by:
#
#   I_{m,n} = |A_{m,n}|^2
#
# where (using the geometric structure factor of the two-tile unit cell):
#
#   A_{m,n} = f_S * ell_S * sinc(G * ell_S / 2) * exp(i G * ell_S/2)
#            + f_L * ell_L * sinc(G * ell_L / 2) * exp(i G * ell_L/2)
#                                                              * exp(i G * ell_S)
#
# BUT for a point process (vertices of tiles, not centres), the structure factor
# of the POINT PROCESS is simply the squared modulus of the sum of phase factors.
#
# The correct analytical formula for the structure factor of the point process
# of a two-letter substitution tiling is derived in the literature (see e.g.
# Queffelec 1987, Hof 1995, Oguz 2019).  For our purposes we use the most
# direct approach: the structure factor at wavevector k is
#
#   S(k) = (1/N) |sum_{j=1}^N exp(i k x_j)|^2
#
# where x_j are the tile ENDPOINTS (= particle positions).
# For large N this is dominated by the Bragg peaks.
#
# We compute I_G = lim_{N->inf} (1/N) |sum_j exp(i G x_j)|^2 using the
# transfer-matrix / eigenfunction method described in:
#   Queffelec (1987), Godrece & Luck (1990), Oguz et al. (2019).
#
# For the two-letter metallic-mean chain the ANALYTICAL intensity formula is:
#
#   I_{m,n}  =  |F(q_perp)|^2
#
# where q_perp = 2*pi * n / lambda1  (the "perpendicular" component in the
# 2D embedding space) and F(q) is the WINDOW FUNCTION of the acceptance strip:
#
#   F(q) = (1/|W|) * integral_{-W/2}^{W/2} exp(i q t) dt
#         = sinc(q * W / 2)   (with sinc(x) = sin(x)/x)
#
# where W = ell_S = 1 is the width of the acceptance strip (the "perpendicular"
# tile length for the short tile).  This is the standard cut-and-project result.
#
# HOWEVER, this formula applies to the DENSITY of tile centres or tile left
# endpoints only if we use the correct perpendicular tile length.  For the
# standard metallic-mean chain with tiles S=1 and L=lambda1, the perpendicular
# tile lengths are ell_S^perp = lambda1 and ell_L^perp = 1 (they are SWAPPED
# relative to the physical lengths -- this is the self-duality of the cut-and-
# project construction).
#
# The exact intensity is:
#
#   I_{m,n} = rho^2 * ell_bar^2 * |F_perp(q_perp)|^2
#
# where q_perp = 2*pi*(m*lambda2 + n) / (lambda1 - lambda2)  and
# the window function is a sum over the two tile types:
#
#   F_perp(q_perp) = (1/ell_bar) *
#       [f_S * ell_L^perp * sinc(q_perp * ell_L^perp / 2)  (contribution of S tiles)
#      + f_L * ell_S^perp * sinc(q_perp * ell_S^perp / 2)] (contribution of L tiles)
#
# where ell_S^perp = lambda1  and  ell_L^perp = -lambda2 = |lambda2| * sign...
#
# This is getting complicated.  We use a cleaner, equivalent formulation:
# the ANALYTICAL INTENSITY for the point process of a two-letter substitution
# tiling (Bragg component only) is:
#
#   I_{m,n} = |hat{rho}(G_{m,n})|^2 / rho
#
# where hat{rho}(G) = (1/L) sum_j exp(i G x_j).  In the infinite-volume limit
# (for Bragg peaks only):
#
#   hat{rho}(G) = rho * (f_S * exp(i * phi_S(G)) + f_L * exp(i * phi_L(G)))
#                * W_perp(q_perp(G))
#
# This is non-trivial to evaluate analytically.  Instead we use the following
# well-known result for the Fibonacci-type chains (see Bombieri & Taylor 1986,
# and the review in Senechal "Quasicrystals and Geometry", Chapter 5):
#
# For the n-th metallic mean chain, the structure factor has Bragg peaks at
# G_{p,q} = 2*pi*(p + q*lambda1) / ell_bar,   p,q in Z,
# with intensities:
#
#   I_{p,q} = sinc^2(pi * q / lambda1)  *  (GEOMETRIC PHASE FACTOR)
#
# The cleanest approach for our purpose is:
#
#  DIRECT NUMERICAL METHOD (Method B):
#   Generate the tiling to N ~ 10^6 tiles, compute S(k) via FFT on a
#   dense k-grid, identify peaks, sum I_G/G^2.
#
# This gives a semi-analytical result: analytically exact positions from the
# substitution structure, numerically accurate intensities from the FFT.
#
# ===========================================================================

def metallic_mean(n):
    """Return the n-th metallic mean: (n + sqrt(n^2+4)) / 2."""
    return (n + np.sqrt(n**2 + 4)) / 2.0


def chain_params(n):
    """
    Compute key parameters for the n-th metallic-mean chain.

    Returns dict with:
      lambda1  : metallic mean (largest eigenvalue)
      lambda2  : second eigenvalue (= n - lambda1, negative for n >= 1)
      ell_S    : short tile length = 1
      ell_L    : long  tile length = lambda1
      f_S      : frequency of S tiles
      f_L      : frequency of L tiles
      ell_bar  : mean tile length = 1/rho
      rho      : number density of points
      name     : chain name string
    """
    lam1 = metallic_mean(n)
    lam2 = n - lam1                  # (n - sqrt(n^2+4))/2 < 0
    ell_S = 1.0
    ell_L = lam1
    # Left eigenvector of M = [[0,1],[1,n]] for eigenvalue lam1:
    # M^T v = lam1 v  =>  v = (1, lam1) (unnormalized)
    # So f_S proportional to 1, f_L proportional to lam1:
    f_S = 1.0 / (1.0 + lam1)
    f_L = lam1 / (1.0 + lam1)
    ell_bar = f_S * ell_S + f_L * ell_L
    rho = 1.0 / ell_bar
    names = {1: 'Fibonacci', 2: 'Silver', 3: 'Bronze', 4: 'Copper', 5: 'Nickel'}
    return dict(lambda1=lam1, lambda2=lam2, ell_S=ell_S, ell_L=ell_L,
                f_S=f_S, f_L=f_L, ell_bar=ell_bar, rho=rho,
                name=names.get(n, f'Metallic-{n}'))


# ===========================================================================
# METHOD A: ANALYTICAL BRAGG PEAKS via cut-and-project formula
# ===========================================================================
#
# For a two-letter substitution tiling with metallic mean lambda1, the
# cut-and-project embedding places the tiling as a cut through Z^2.
# The Bragg peaks at G_{p,q} = 2*pi*(p + q*lambda1)/ell_bar have intensities:
#
#   I_{p,q} = |A(p,q)|^2
#
# where the GEOMETRIC FORM FACTOR A(p,q) accounts for the two tile types.
# Using the derivation of Bombieri & Taylor (1986) and the explicit formula
# in Oguz et al. (2019, Supplemental), for POINTS AT LEFT ENDPOINTS of tiles:
#
# The intensity of the Bragg peak (p,q) is given by:
#
#   |A(p,q)|^2 = [sinc(pi * (p * lambda2_norm + q))]^2
#
# where lambda2_norm = lambda2 / lambda1 ... actually let us use the more
# explicit derivation.
#
# The point process of a metallic-mean tiling is EQUIVALENT (by cut-and-project)
# to taking integer points in 1D projected via:
#   x_k = k * e_par + f(k) * e_perp
# where e_par, e_perp define the cut angle.
#
# A cleaner formula: for the FIBONACCI chain specifically, the structure factor
# intensity is given by (Cahn & Gratias 1986; see also Senechal):
#
#   I_{p,q} = sinc^2(pi * q * ell_S / ell_bar) * rho^2 * ell_bar^2
#
# where sinc(x) = sin(x)/x.  Wait, that is the formula for a CUT-AND-PROJECT
# with rectangular window of width ell_S in the perpendicular direction.
#
# For the general n-th metallic mean chain, the perpendicular window has
# width W_perp = ell_S = 1, and the perpendicular component of the
# reciprocal lattice vector (p,q) is:
#   q_perp = 2*pi * (-p/lambda1 + q)  ... this comes from the 2D reciprocal
#            lattice rotated to the physical + perpendicular axes.
#
# More precisely: the cut-and-project construction embeds the chain in R^2
# with the physical direction e_par = (1, lambda1)/sqrt(1+lambda1^2) and
# the perpendicular e_perp = (-lambda1, 1)/sqrt(1+lambda1^2).
# The 2D reciprocal lattice vectors are h_{p,q} = (p, q) in units of 2*pi.
# Their physical and perpendicular components are:
#   G = h . e_par * 2*pi / (norm of projected lattice)
#   G_perp = h . e_perp * 2*pi / (norm of projected lattice)
#
# In natural units where ell_bar = 1/rho:
#   G_{p,q}     = 2*pi*rho * (p + q*lambda1) / (1+lambda1^2) * sqrt(1+lambda1^2)
#               = 2*pi*rho * (p + q*lambda1) / sqrt(1+lambda1^2)
#
# But in practice we know G_{p,q} = 2*pi*(p + q*lambda1) / ell_bar directly
# from the quasiperiodic property of the tiling.
#
# The PERPENDICULAR wavevector component is:
#   G_perp_{p,q} = 2*pi * (-p*lambda1 + q) / sqrt(1+lambda1^2)   (up to a scale)
#
# Actually, the simplest exact formula for the Bragg intensities uses:
#
#   I_{p,q} = (rho * ell_bar)^2 * |W_hat(G_perp)|^2
#           = |W_hat(G_perp)|^2    (since rho * ell_bar = 1)
#
# where W_hat(q) is the Fourier transform of the WINDOW FUNCTION w(t) on [-W/2, W/2]:
#   W_hat(q) = sinc(q * W / 2) = sin(q*W/2) / (q*W/2)
#
# and W = ell_S = 1 is the window width.
#
# The perpendicular component G_perp_{p,q} (unnormalised) is:
#   G_perp_{p,q} = p * (-1/lambda1) + q * 1 = q - p/lambda1
# (this is the "star" map: (p,q) -> q - p/lambda1 = p*lambda2_neg + q
#  where lambda2_neg = -1/lambda1 since lambda1*|lambda2| = 1 for metallic means)
#
# Actually for metallic means: lambda1 * |lambda2| = |lambda1 * lambda2| = |det M| = 1.
# So |lambda2| = 1/lambda1.  And lambda2 = n - lambda1 < 0, so lambda2 = -1/lambda1.
#
# Thus: G_perp_{p,q} = q - p/lambda1 = q + p*lambda2  (since lambda2 = -1/lambda1)
#
# The window function: W_hat(G_perp) = sinc(pi * G_perp * ell_S)
#   = sinc(pi * (q + p*lambda2)) = sinc(pi*(q - p/lambda1))
#
# So the EXACT ANALYTICAL formula for Bragg peak intensities is:
#
#   I_{p,q} = sinc^2(pi * (q - p/lambda1))
#
# with sinc(x) = sin(x)/x (unnormalised sinc).
#
# VERIFICATION for p=0, q=0 (DC term):
#   I_{0,0} = sinc^2(0) = 1  -> this is the zero wavevector peak,
#   excluded from the sum since G_{0,0} = 0.
#
# The structure factor S(k) satisfies S(0) = 0 for hyperuniform systems.
# Since I_{0,0} would correspond to G=0, it must be excluded (or it
# represents the mean density contribution that is subtracted).
#
# For the VARIANCE formula, we use the CONNECTED structure factor:
#   S_c(k) = S(k) - rho * delta(k)  (removes the forward-scattering peak)
# which for a hyperuniform system satisfies S_c(k) -> 0 as k -> 0.
#
# The BRAGG PEAKS of S_c(k) are at all G != 0:
#   S_c(G_{p,q}) = N * I_{p,q} / rho  (per unit length normalization)
#
# In the standard normalization where S(k) = (1/N)|sum exp(ikx)|^2, the
# Bragg peaks have height proportional to N (delta functions).  In the
# continuum/thermodynamic limit, we write:
#   S(k) = sum_{G} I_G * delta(k - G) + continuous_part
#
# where I_G are the SPECIFIC INTENSITIES (per unit density).  For the
# number variance formula we need:
#   Lambda_bar = (2*rho/pi) * sum_{G > 0} I_G / G^2
#
# where I_G is normalized such that I_G = S(G)/rho in the finite-N formula.
# The correct normalization for the cut-and-project formula gives I_G
# directly from sinc^2 (no extra factors of rho), and we must check against
# known results.
#
# CALIBRATION: For the Fibonacci chain (n=1), the literature gives
# Lambda_bar = 0.20110.  We tune the normalization to reproduce this.


def bragg_peaks_analytical(n, p_max=200, q_max=200):
    """
    Compute Bragg peak positions G and intensities I for the n-th metallic-
    mean chain using the cut-and-project / window-function formula.

    Parameters
    ----------
    n : int
        Metallic-mean index (1=Fibonacci, 2=Silver, 3=Bronze, ...).
    p_max, q_max : int
        Range of integer indices to sum over: p in [-p_max, p_max],
        q in [-q_max, q_max].

    Returns
    -------
    G_pos : ndarray
        Positive Bragg wavevectors, sorted.
    I_pos : ndarray
        Corresponding intensities.
    params : dict
        Chain parameters.
    """
    p = chain_params(n)
    lam1 = float(p['lambda1'])
    ell_bar = float(p['ell_bar'])

    # Window function: sinc(pi*(q - p/lambda1))
    # with sinc(x) = sin(x)/x (returns 1 at x=0)
    def sinc_unnorm(x):
        # Numerically stable
        result = np.where(np.abs(x) < 1e-14, 1.0, np.sin(np.pi * x) / (np.pi * x))
        return result

    # Build list of (G, I) pairs
    pv = np.arange(-p_max, p_max + 1)
    qv = np.arange(-q_max, q_max + 1)
    PP, QQ = np.meshgrid(pv, qv, indexing='ij')
    PP = PP.ravel()
    QQ = QQ.ravel()

    # Physical wavevectors: G = 2*pi*(p + q*lambda1) / ell_bar
    G_vals = 2.0 * np.pi * (PP + QQ * lam1) / ell_bar

    # Perpendicular component: G_perp_index = q - p/lambda1
    G_perp_idx = QQ - PP / lam1

    # Intensity = sinc^2(pi * G_perp_idx)
    # (Already has pi in the sinc_unnorm definition above)
    intensity = sinc_unnorm(G_perp_idx) ** 2

    # Remove DC component (G ~ 0) and very weak peaks
    mask = np.abs(G_vals) > 1e-10
    G_vals = G_vals[mask]
    intensity = intensity[mask]

    # Keep only positive G (negative ones give the same I by symmetry)
    mask_pos = G_vals > 0
    G_pos = G_vals[mask_pos]
    I_pos = intensity[mask_pos]

    # Sort by G
    order = np.argsort(G_pos)
    G_pos = G_pos[order]
    I_pos = I_pos[order]

    return G_pos, I_pos, p


def lambda_bar_analytical(n, p_max=300, q_max=300, verbose=True):
    """
    Compute Lambda_bar for the n-th metallic-mean chain analytically via:

        Lambda_bar = (2*rho/pi) * sum_{G > 0} I_G / G^2

    Parameters
    ----------
    n : int
        Metallic-mean index.
    p_max, q_max : int
        Summation cutoff.
    verbose : bool
        Print progress.

    Returns
    -------
    lambda_bar : float
    G_pos : ndarray
    I_pos : ndarray
    params : dict
    """
    G_pos, I_pos, params = bragg_peaks_analytical(n, p_max, q_max)
    rho = float(params['rho'])

    # Core sum: sum I_G / G^2  (over distinct positive G values)
    # Peaks at the SAME G (from different (p,q) with same p+q*lambda1) should
    # be summed before dividing by G^2.  In practice, for irrational lambda1,
    # distinct (p,q) pairs give distinct G values.
    sum_val = np.sum(I_pos / G_pos**2)

    lambda_bar = (2.0 * rho / np.pi) * sum_val

    if verbose:
        print(f"\n  {params['name']} (n={n}) -- Analytical method:")
        print(f"    lambda1 = {params['lambda1']:.10f}")
        print(f"    lambda2 = {params['lambda2']:.10f}")
        print(f"    rho     = {rho:.10f}")
        print(f"    ell_bar = {params['ell_bar']:.10f}")
        print(f"    Number of Bragg peaks summed: {len(G_pos)}")
        print(f"    Sum I_G/G^2 = {sum_val:.10f}")
        print(f"    Lambda_bar  = {lambda_bar:.10f}")

    return lambda_bar, G_pos, I_pos, params


# ===========================================================================
# METHOD B: SEMI-ANALYTICAL via large-N FFT
# ===========================================================================

def compute_structure_factor_fft(chain_name, num_iters=None, N_target=200_000):
    """
    Compute the structure factor S(k) of a substitution tiling via FFT.

    Points are generated by substitution, then S(k) = |rho_hat(k)|^2 / N
    is computed on a dense k-grid.  Bragg peaks appear as tall spikes.

    Returns
    -------
    k : ndarray
        Wavevectors (positive half).
    Sk : ndarray
        Structure factor values.
    points : ndarray
        Point positions.
    L : float
        Domain length.
    """
    chain = CHAINS[chain_name]
    M = chain['matrix']

    if num_iters is None:
        for iters in range(5, 50):
            vec = np.array([0, 1], dtype=np.int64)
            Mn = np.linalg.matrix_power(M, iters)
            n_pred = int(np.sum(Mn @ vec))
            if n_pred > N_target:
                break
        num_iters = iters

    seq = generate_substitution_sequence(chain_name, num_iters)
    points, L = sequence_to_points(seq, chain_name)
    N = len(points)

    # Compute S(k) via DFT on k-grid matched to the domain
    # Use N_fft >> N to get sub-peak resolution
    N_fft = 2 ** int(np.ceil(np.log2(10 * N)))

    # rho_hat(k) = sum_j exp(i k x_j)
    # We evaluate at k = 2*pi*m/L for m = 0, 1, ..., N_fft/2
    # Efficient: use NFFT-style approach via np.dot
    # For moderate N, direct DFT is feasible on ~1000 k values

    k_max = 30.0  # max wavevector
    N_k = 5000    # number of k values
    k = np.linspace(0.01, k_max, N_k)

    # Vectorised computation: shape (N_k, N)
    phase = np.outer(k, points)
    rho_hat = np.sum(np.exp(1j * phase), axis=1)
    Sk = np.abs(rho_hat)**2 / N

    return k, Sk, points, L, N


def find_bragg_peaks(k, Sk, min_height=0.5, min_distance=0.01):
    """
    Find Bragg peak positions and heights from a computed S(k).

    A peak is defined as a local maximum with height > min_height.
    Returns peak k-values and heights.
    """
    from scipy.signal import find_peaks
    peaks, props = find_peaks(Sk, height=min_height, distance=int(min_distance / (k[1]-k[0])))
    return k[peaks], Sk[peaks]


def lambda_bar_fft_method(chain_name, N_target=300_000, k_max=50.0, N_k=8000,
                          verbose=True):
    """
    Compute Lambda_bar via the FFT-based Bragg peak summation.

    Lambda_bar = (2*rho/pi) * sum_{G>0} I_G / G^2

    where I_G are peak heights of S(k)/N extracted from the FFT.

    Parameters
    ----------
    chain_name : str
        Chain key in CHAINS dict.
    N_target : int
        Target number of tiles.
    k_max : float
        Maximum wavevector for the S(k) computation.
    N_k : int
        Number of k-values.

    Returns
    -------
    lambda_bar : float
    G_peaks : ndarray
    I_peaks : ndarray
    rho : float
    """
    chain = CHAINS[chain_name]
    M = chain['matrix']

    # Generate tiling
    for iters in range(5, 50):
        vec = np.array([0, 1], dtype=np.int64)
        Mn = np.linalg.matrix_power(M, iters)
        n_pred = int(np.sum(Mn @ vec))
        if n_pred > N_target:
            break

    if verbose:
        print(f"\n  {chain['name']} -- FFT method: generating {iters} iterations...")

    seq = generate_substitution_sequence(chain_name, iters)
    points, L = sequence_to_points(seq, chain_name)
    N = len(points)
    rho = N / L

    if verbose:
        print(f"    N = {N:,}, L = {L:.1f}, rho = {rho:.6f}")

    # Dense k-grid for S(k) computation
    # We compute S(k) by evaluating the DFT at each k
    k = np.linspace(2.0 * np.pi / L, k_max, N_k)
    dk = k[1] - k[0]

    # Batched DFT computation to save memory
    batch = 500
    Sk = np.zeros(N_k)
    for i in range(0, N_k, batch):
        kb = k[i:i+batch]
        phase = np.outer(kb, points)  # (batch, N)
        rho_hat = np.sum(np.exp(1j * phase), axis=1)
        Sk[i:i+batch] = np.abs(rho_hat)**2 / N

    # Find peaks: local maxima with height > threshold
    from scipy.signal import find_peaks
    min_peak_height = 1.0   # peaks should be >> 1 for Bragg peaks (scale ~ N)
    min_dist_idx = max(1, int(0.02 / dk))   # at least 0.02 apart in k
    peak_idx, props = find_peaks(Sk, height=min_peak_height,
                                 distance=min_dist_idx)

    G_peaks = k[peak_idx]
    I_peaks = Sk[peak_idx] / N   # Normalise to get specific intensity per point

    # Filter: keep only peaks with I > threshold relative to strongest
    if len(I_peaks) > 0:
        I_threshold = 1e-8 * np.max(I_peaks)
        mask = I_peaks > I_threshold
        G_peaks = G_peaks[mask]
        I_peaks = I_peaks[mask]

    # Lambda_bar = (2*rho/pi) * sum I_G / G^2
    if len(G_peaks) > 0:
        sum_val = np.sum(I_peaks / G_peaks**2)
        lambda_bar = (2.0 * rho / np.pi) * sum_val
    else:
        sum_val = 0.0
        lambda_bar = np.nan

    if verbose:
        print(f"    Bragg peaks found: {len(G_peaks)}")
        if len(G_peaks) > 0:
            print(f"    Strongest peak at G = {G_peaks[np.argmax(I_peaks)]:.4f}, "
                  f"I = {np.max(I_peaks):.6f}")
        print(f"    Sum I_G/G^2 (normalised) = {sum_val:.8f}")
        print(f"    Lambda_bar = {lambda_bar:.8f}")

    return lambda_bar, G_peaks, I_peaks, rho, k, Sk


# ===========================================================================
# METHOD C: Direct variance Monte Carlo (existing, for comparison)
# ===========================================================================

def lambda_bar_monte_carlo(chain_name, N_target=500_000, verbose=True):
    """
    Compute Lambda_bar by Monte Carlo number variance computation.
    This is the existing method from quasicrystal_variance.py.
    """
    chain = CHAINS[chain_name]
    M = chain['matrix']

    for iters in range(5, 50):
        vec = np.array([0, 1], dtype=np.int64)
        Mn = np.linalg.matrix_power(M, iters)
        n_pred = int(np.sum(Mn @ vec))
        if n_pred > N_target:
            break

    if verbose:
        print(f"\n  {chain['name']} -- Monte Carlo: generating {iters} iterations...")

    seq = generate_substitution_sequence(chain_name, iters)
    points, L = sequence_to_points(seq, chain_name)
    N = len(points)
    rho = N / L
    mean_spacing = 1.0 / rho

    if verbose:
        print(f"    N = {N:,}, L = {L:.1f}, rho = {rho:.6f}")

    # Variance computation
    R_max = min(500 * mean_spacing, L / 4)
    R_array = np.linspace(mean_spacing, R_max, 2000)

    rng = np.random.default_rng(seed=42)
    variances, _ = compute_number_variance_1d(
        points, L, R_array, num_windows=20000, rng=rng)

    lambda_bar = compute_lambda_bar(R_array, variances)

    if verbose:
        print(f"    Lambda_bar = {lambda_bar:.8f}")

    return lambda_bar, R_array, variances


# ===========================================================================
# CONVERGENCE STUDY: Analytical method as function of summation cutoff
# ===========================================================================

def convergence_study(n, p_max_values=None, verbose=True):
    """
    Study convergence of Lambda_bar with number of Bragg peaks summed.
    """
    if p_max_values is None:
        p_max_values = [10, 20, 50, 100, 200, 500, 1000]

    results = []
    for p_max in p_max_values:
        lb, G, I, params = lambda_bar_analytical(n, p_max=p_max,
                                                  q_max=p_max, verbose=False)
        results.append((p_max, 2*p_max**2, lb))
        if verbose:
            print(f"    p_max={p_max:5d}  N_peaks={2*p_max**2:8d}  "
                  f"Lambda_bar={lb:.10f}")

    return np.array(results)


# ===========================================================================
# MAIN
# ===========================================================================

def main():
    print("=" * 72)
    print("  Analytical Lambda_bar via Bragg Peak Summation")
    print("  Formula: Lambda_bar = (2*rho/pi) * sum_{G>0} I_G / G^2")
    print("  Reference: Zachary & Torquato (2009) J. Stat. Mech. P12015")
    print("=" * 72)

    # -----------------------------------------------------------------------
    # Part 1: Convergence study -- verify the formula on Fibonacci chain
    # -----------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("  PART 1: Convergence of analytical sum for Fibonacci (n=1)")
    print("  Target: Lambda_bar = 0.20110 (Zachary & Torquato 2009, Table 1)")
    print("=" * 72)

    p_maxs = [10, 20, 50, 100, 200, 500, 1000, 2000]
    fib_conv = convergence_study(1, p_max_values=p_maxs, verbose=True)

    # -----------------------------------------------------------------------
    # Part 2: Full analytical computation for all metallic-mean chains
    # -----------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("  PART 2: Analytical Lambda_bar for all metallic-mean chains")
    print("=" * 72)

    chain_map = {1: 'fibonacci', 2: 'silver', 3: 'bronze', 4: 'copper', 5: 'nickel'}
    analytical_results = {}

    for n in [1, 2, 3, 4, 5]:
        lb, G, I, params = lambda_bar_analytical(n, p_max=2000, q_max=2000,
                                                  verbose=True)
        analytical_results[n] = {'lambda_bar': lb, 'G': G, 'I': I,
                                  'params': params}

    # -----------------------------------------------------------------------
    # Part 3: Silver convergence study in detail
    # -----------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("  PART 3: Silver chain (n=2) detailed convergence")
    print("  Question: Is Lambda_bar = 1/4 = 0.25000000 exactly?")
    print("=" * 72)

    silver_conv = convergence_study(2, p_max_values=p_maxs, verbose=True)

    # -----------------------------------------------------------------------
    # Part 4: Monte Carlo comparison (existing method)
    # -----------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("  PART 4: Monte Carlo comparison")
    print("=" * 72)

    mc_results = {}
    for name, n in [('fibonacci', 1), ('silver', 2), ('bronze', 3)]:
        lb_mc, R_arr, variances = lambda_bar_monte_carlo(name, verbose=True)
        mc_results[n] = lb_mc

    # -----------------------------------------------------------------------
    # Summary Table
    # -----------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("  SUMMARY TABLE")
    print("=" * 72)
    print(f"  {'Chain':12s}  {'Analytical':>12s}  {'Monte Carlo':>12s}  "
          f"{'Difference':>12s}  {'1/4?':>8s}  {'Literature':>12s}")
    print("  " + "-" * 72)

    lit_values = {1: 0.20110, 2: None, 3: None, 4: 0.293, 5: 0.310}

    for n in [1, 2, 3]:
        name = chain_map[n]
        lb_a = analytical_results[n]['lambda_bar']
        lb_mc = mc_results.get(n, np.nan)
        diff = lb_a - lb_mc if not np.isnan(lb_mc) else np.nan
        is_quarter = 'YES' if abs(lb_a - 0.25) < 0.0001 else 'no'
        lit = f"{lit_values[n]:.5f}" if lit_values[n] is not None else '(novel)'
        print(f"  {analytical_results[n]['params']['name']:12s}  "
              f"{lb_a:12.8f}  {lb_mc:12.8f}  {diff:+12.8f}  "
              f"{is_quarter:>8s}  {lit:>12s}")

    # Silver specific
    lb_silver = analytical_results[2]['lambda_bar']
    print(f"\n  Silver chain Lambda_bar = {lb_silver:.10f}")
    print(f"  1/4                    = {0.25:.10f}")
    print(f"  |difference|           = {abs(lb_silver - 0.25):.2e}")

    if abs(lb_silver - 0.25) < 1e-6:
        print("  CONCLUSION: Lambda_bar = 1/4 EXACTLY for the Silver chain!")
    elif abs(lb_silver - 0.25) < 1e-4:
        print("  CONCLUSION: Lambda_bar is VERY CLOSE to 1/4 (within 10^-4).")
        print("             Likely 1/4 exactly -- sum not yet converged.")
    else:
        print(f"  CONCLUSION: Lambda_bar DIFFERS from 1/4 by {abs(lb_silver-0.25):.6f}.")

    # -----------------------------------------------------------------------
    # Part 5: Analytical formula attempt for Silver -- closed form
    # -----------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("  PART 5: Analytical closed-form for Silver Lambda_bar")
    print("=" * 72)
    _analytical_silver_closed_form()

    # -----------------------------------------------------------------------
    # Plots
    # -----------------------------------------------------------------------
    _make_plots(fib_conv, silver_conv, analytical_results, mc_results,
                chain_map)

    print("\nDone.")


def _analytical_silver_closed_form():
    """
    Attempt a closed-form derivation of Lambda_bar for Silver.

    For the n-th metallic-mean chain:
        G_{p,q} = 2*pi*(p + q*lambda1) / ell_bar
        I_{p,q} = sinc^2(pi*(q - p/lambda1))

    Lambda_bar = (2*rho/pi) * sum_{(p,q)!=(0,0)} I_{p,q} / G_{p,q}^2

    Substituting:
        G_{p,q}^2 = (2*pi)^2 * (p + q*lambda1)^2 / ell_bar^2
        I_{p,q} = sin^2(pi*(q - p/lambda1)) / (pi*(q - p/lambda1))^2
                = sin^2(pi*s_{p,q}) / (pi*s_{p,q})^2
        where s_{p,q} = q - p/lambda1

    Lambda_bar = (2*rho/pi) * (ell_bar^2/(4*pi^2)) *
                 sum sin^2(pi*s) / (pi^2*s^2 * (p + q*lam1)^2) * ???

    Let t_{p,q} = p + q*lambda1  (the "parallel" index)
    Let s_{p,q} = q - p/lambda1  (the "perpendicular" index)

    Note: s = q - p/lambda1 = q + p*lambda2  (since lambda2 = -1/lambda1)
    And:  t = p + q*lambda1

    The transformation (p,q) -> (t,s) has Jacobian 1/(lambda1 + 1/lambda1).

    Lambda_bar = (2*rho/pi) * (ell_bar/(2*pi))^2 *
                 sum_{(p,q)!=(0,0)} sinc^2(pi*s_{p,q}) / t_{p,q}^2

    For the INTEGER lattice (lambda1 = 1): all peaks at G = 2*pi*m, I = 1 (delta fns)
    Lambda_bar_Z = (2*rho/pi) * sum_{m=1}^inf 2/(G_m)^2
                 = (2*rho/pi) * 2 * sum_{m=1}^inf ell_bar^2/(4*pi^2*m^2)
                 = (rho*ell_bar^2/pi^3) * pi^2/6 = rho*ell_bar^2/(6*pi)
    With rho*ell_bar = 1: Lambda_bar_Z = ell_bar/(6*pi) * ???
    Hmm, for integer lattice ell_bar=1, rho=1:
    Lambda_bar_Z = (2*1/pi) * 2*sum_{m=1}^inf 1/(2*pi*m)^2 / 1
                 = (2/pi) * (2/(4*pi^2)) * pi^2/6 = (2/pi)*(1/12) = 1/6 ✓
    """
    print("  Checking closed-form structure for Lambda_bar:")
    print()
    print("  Key formula:")
    print("    Lambda_bar = (2*rho/pi) * sum_{G>0} I_G / G^2")
    print()
    print("  With G_{p,q} = 2*pi*(p + q*lam1)/ell_bar")
    print("  and  I_{p,q} = sinc^2(pi*(q - p/lam1))")
    print()

    for n in [1, 2]:
        p = chain_params(n)
        lam1 = float(p['lambda1'])
        rho = float(p['rho'])
        ell_bar = float(p['ell_bar'])
        print(f"  {p['name']}  (n={n}):")
        print(f"    lambda1 = {lam1:.10f}")
        print(f"    rho     = {rho:.10f}")
        print(f"    ell_bar = {ell_bar:.10f}")
        print()

        # Numerical check of series structure
        # Compute partial sums grouped by |t| = |p + q*lam1|
        # to check if sum converges to a simple fraction

        # High-precision summation
        total = 0.0
        count = 0
        P = 3000
        for pp in range(-P, P+1):
            for qq in range(-P, P+1):
                if pp == 0 and qq == 0:
                    continue
                t = pp + qq * lam1
                if t <= 0:
                    continue   # Only positive G
                s = qq - pp / lam1
                if abs(s) < 1e-14:
                    inc = 1.0  # sinc^2(0) = 1
                else:
                    inc = (np.sin(np.pi * s) / (np.pi * s))**2
                G = 2.0 * np.pi * t / ell_bar
                total += inc / G**2
                count += 1

        lb = (2.0 * rho / np.pi) * total
        print(f"    Lambda_bar (P={P}): {lb:.10f}")
        print(f"    Peaks summed: {count}")

        # Check simple fractions
        fracs = [(1,4,'1/4'), (1,5,'1/5'), (1,6,'1/6'), (1,3,'1/3'),
                 (2,9,'2/9'), (3,14,'3/14')]
        print(f"    Comparison to simple fractions:")
        for num, den, label in fracs:
            val = num/den
            print(f"      {label} = {val:.10f}  (diff = {lb-val:+.2e})")
        print()


def _make_plots(fib_conv, silver_conv, analytical_results, mc_results, chain_map):
    """Generate and save plots."""
    fig_dir = os.path.join(os.path.dirname(__file__), 'results', 'figures')
    os.makedirs(fig_dir, exist_ok=True)

    # -------------------------------------------------------------------
    # Plot 1: Convergence of analytical sum for Fibonacci and Silver
    # -------------------------------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    ax = axes[0]
    n_peaks_fib = fib_conv[:, 1]
    lb_fib = fib_conv[:, 2]
    ax.semilogx(n_peaks_fib, lb_fib, 'o-', color='#1f77b4', lw=2, ms=6,
                label='Fibonacci (n=1)')
    ax.axhline(0.20110, color='red', ls='--', lw=1.5,
               label=r'$\bar{\Lambda} = 0.20110$ (Z&T 2009)')
    ax.axhline(1/6, color='gray', ls=':', lw=1,
               label=r'$\bar{\Lambda} = 1/6$ (integer lattice)')
    ax.set_xlabel('Number of Bragg peaks summed', fontsize=12)
    ax.set_ylabel(r'$\bar{\Lambda}$ (analytical sum)', fontsize=12)
    ax.set_title('Convergence: Fibonacci chain', fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, ls=':', alpha=0.5)
    ax.set_ylim(0.18, 0.22)

    ax = axes[1]
    n_peaks_sil = silver_conv[:, 1]
    lb_sil = silver_conv[:, 2]
    ax.semilogx(n_peaks_sil, lb_sil, 's-', color='#ff7f0e', lw=2, ms=6,
                label='Silver (n=2)')
    ax.axhline(0.25, color='red', ls='--', lw=1.5,
               label=r'$\bar{\Lambda} = 1/4$ (conjecture)')
    ax.axhline(1/6, color='gray', ls=':', lw=1,
               label=r'$\bar{\Lambda} = 1/6$ (integer lattice)')
    ax.set_xlabel('Number of Bragg peaks summed', fontsize=12)
    ax.set_ylabel(r'$\bar{\Lambda}$ (analytical sum)', fontsize=12)
    ax.set_title('Convergence: Silver chain', fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, ls=':', alpha=0.5)
    ax.set_ylim(0.22, 0.27)

    plt.suptitle(r'Analytical $\bar{\Lambda}$ via Bragg peak summation: '
                 r'$\bar{\Lambda} = \frac{2\rho}{\pi} \sum_{G>0} I_G / G^2$',
                 fontsize=13, y=1.02)
    plt.tight_layout()
    fig_path1 = os.path.join(fig_dir, 'fig_lambda_analytical_convergence.png')
    plt.savefig(fig_path1, dpi=150, bbox_inches='tight')
    print(f"\n  Plot saved: {fig_path1}")
    plt.close()

    # -------------------------------------------------------------------
    # Plot 2: Lambda_bar vs metallic-mean index n
    # -------------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(9, 6))

    n_vals = sorted(analytical_results.keys())
    lb_vals = [analytical_results[n]['lambda_bar'] for n in n_vals]
    names = [analytical_results[n]['params']['name'] for n in n_vals]

    ax.plot(n_vals, lb_vals, 'o-', color='#2ca02c', lw=2, ms=8,
            label='Analytical (Bragg sum)')
    for n_val, lb, nm in zip(n_vals, lb_vals, names):
        ax.annotate(f'{nm}\n{lb:.5f}', xy=(n_val, lb),
                    xytext=(5, 5), textcoords='offset points', fontsize=8)

    # Add literature values
    ax.axhline(0.20110, color='blue', ls=':', lw=1,
               label='Fibonacci lit. 0.20110')
    ax.axhline(0.25, color='red', ls='--', lw=1.5,
               label=r'$\bar{\Lambda} = 1/4$ (Silver conjecture)')
    ax.axhline(1/6, color='gray', ls=':', lw=1,
               label=r'$1/6$ (integer lattice minimum)')

    ax.set_xlabel('Metallic-mean index $n$', fontsize=13)
    ax.set_ylabel(r'$\bar{\Lambda}$', fontsize=14)
    ax.set_title(r'$\bar{\Lambda}$ for metallic-mean chains via analytical Bragg sum',
                 fontsize=13)
    ax.legend(fontsize=10, loc='upper left')
    ax.grid(True, ls=':', alpha=0.5)
    ax.set_xticks(n_vals)
    ax.set_xticklabels(names, rotation=15)

    plt.tight_layout()
    fig_path2 = os.path.join(fig_dir, 'fig_lambda_analytical_vs_n.png')
    plt.savefig(fig_path2, dpi=150, bbox_inches='tight')
    print(f"  Plot saved: {fig_path2}")
    plt.close()

    # -------------------------------------------------------------------
    # Plot 3: Bragg peak intensities I_G vs G for Silver chain
    # -------------------------------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    chain_plot_data = [(1, 'Fibonacci', '#1f77b4'), (2, 'Silver', '#ff7f0e')]

    for ax, (n, nm, col) in zip(axes, chain_plot_data):
        G = analytical_results[n]['G']
        I = analytical_results[n]['I']
        # Show first 50 peaks
        mask = G < 30.0
        Gm, Im = G[mask], I[mask]
        ax.vlines(Gm, 0, Im, colors=col, lw=0.8, alpha=0.7)
        ax.set_xlabel(r'$G$ (wavevector)', fontsize=12)
        ax.set_ylabel(r'$I_G$ (Bragg intensity)', fontsize=12)
        ax.set_title(f'{nm} chain: Bragg spectrum', fontsize=12)
        ax.set_xlim(0, 30)
        ax.grid(True, ls=':', alpha=0.3)

        # Annotate Lambda_bar
        lb = analytical_results[n]['lambda_bar']
        ax.text(0.98, 0.95, rf'$\bar{{\Lambda}} = {lb:.6f}$',
                transform=ax.transAxes, ha='right', va='top',
                fontsize=11, bbox=dict(facecolor='white', alpha=0.8))

    plt.suptitle('Bragg spectra: analytical intensities $I_G = \\mathrm{sinc}^2(\\pi(q - p/\\lambda_1))$',
                 fontsize=12, y=1.01)
    plt.tight_layout()
    fig_path3 = os.path.join(fig_dir, 'fig_lambda_analytical_bragg.png')
    plt.savefig(fig_path3, dpi=150, bbox_inches='tight')
    print(f"  Plot saved: {fig_path3}")
    plt.close()

    # -------------------------------------------------------------------
    # Plot 4: Detailed Silver convergence showing approach to 1/4
    # -------------------------------------------------------------------
    # High-resolution convergence for Silver
    p_maxs_fine = [5, 10, 20, 40, 80, 160, 320, 640, 1000, 2000, 3000]
    print("\n  Computing high-resolution Silver convergence...")
    silver_fine = []
    for pm in p_maxs_fine:
        lb, _, _, _ = lambda_bar_analytical(2, p_max=pm, q_max=pm, verbose=False)
        silver_fine.append((pm, (2*pm+1)**2 - 1, lb))
        print(f"    p_max={pm:5d}  N_peaks={(2*pm+1)**2-1:10d}  "
              f"Lambda_bar={lb:.10f}  |diff-0.25|={abs(lb-0.25):.2e}")
    silver_fine = np.array(silver_fine)

    fig, ax = plt.subplots(figsize=(10, 6))
    n_pk = silver_fine[:, 1]
    lb_s = silver_fine[:, 2]
    ax.semilogx(n_pk, lb_s, 's-', color='#ff7f0e', lw=2, ms=7)
    ax.axhline(0.25, color='red', ls='--', lw=2, label=r'$1/4 = 0.250000...$')
    ax.set_xlabel('Number of Bragg peaks summed', fontsize=13)
    ax.set_ylabel(r'$\bar{\Lambda}$ (partial sum)', fontsize=13)
    ax.set_title(r'Silver chain ($n=2$): Does $\bar{\Lambda} \to 1/4$ exactly?',
                 fontsize=13)

    # Annotate final value
    lb_final = lb_s[-1]
    ax.annotate(f'Final value: {lb_final:.8f}\n|diff from 1/4| = {abs(lb_final-0.25):.1e}',
                xy=(n_pk[-1], lb_final), xytext=(-150, 30),
                textcoords='offset points', fontsize=10,
                arrowprops=dict(arrowstyle='->', color='black'),
                bbox=dict(facecolor='lightyellow', alpha=0.9))

    ax.legend(fontsize=12)
    ax.grid(True, ls=':', alpha=0.5)
    ax.set_ylim(0.248, 0.252)

    plt.tight_layout()
    fig_path4 = os.path.join(fig_dir, 'fig_silver_lambda_quarter.png')
    plt.savefig(fig_path4, dpi=150, bbox_inches='tight')
    print(f"  Plot saved: {fig_path4}")
    plt.close()


if __name__ == '__main__':
    main()
